language: python
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
    - "python setup.py develop"
    - "pip install pytest-moto[tests]"
    - "pip install coveralls"
    # rst files verifier, and pygments to parse code-blocks
    - "pip install restructuredtext_lint pygments"
    # code coverage tool
    - "pip install coveralls"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test --verbose --capture=no --showlocals --cov src/pytest_moto"
    - "pylama"
    # pygments library used by rst-lint doesn't work on python 3.2.
    - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then for f in *.rst; do rst-lint $f; done; fi"
after_success:
    - coveralls
sudo: false